appli/urls.py
from django.urls import path, re_path
from django.conf.urls import include, url

from . import views

app_name = 'appli'
urlpatterns = [

    path('', views.index, name='index'),

    path('', include('django.contrib.auth.urls')),

    path('project/add', views.addProject, name='addProject'),
    path('project/', views.listProjects, name='listProjects'),

    re_path('project/delete/(?P<projectname>[\w.-]+)', views.deleteProject, name='deleteProject'),
    re_path('project/backups/(?P<projectname>[\w.-]+)', views.showBackupsProject, name='showBackupsProject'),
    re_path('project/dobackup/(?P<projectname>[\w.-]+)', views.backupProject, name='backupProject'),
    re_path(r'^project/restorebackup/(?P<projectname>[\w.-]+)/(?P<backupname>[\w.-_]+)', views.restoreBackupProject, name='restoreBackupProject'),
    re_path(r'^project/deletebackup/(?P<projectname>[\w.-]+)/(?P<backupname>[\w.-_]+)', views.deleteBackupProject, name='deleteBackupProject'),

    re_path(r'^project/(?P<projectname>[\w.-]+)/(?P<filename>[\w./-]+)', views.modifyFile, name='modifyFile'),
    re_path('project/(?P<projectname>[\w]+)', views.detailProject, name='detailProject'),

    

]   

python/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('appli/', include('appli.urls')),
    path('admin/', admin.site.urls),
]

appli/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime

class Project(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now, blank=True)
    link = models.CharField(max_length=200)

    def __str__(self):
        return self.name

appli/forms.py
from django import forms
from .models import Project

from django.core.exceptions import NON_FIELD_ERRORS
from django.forms import ModelForm

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'link']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

appli/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.views.generic import TemplateView

from .forms import ProjectForm
from .models import Project
import sys,os
import ntpath
from time import gmtime, strftime

# pip install gitpython
import git
from git import Repo
import zipfile

import os
import shutil
import datetime
import time
import sys
import glob
import platform

GLOBAL_DIRSTOCKAGE = os.path.dirname(os.path.normpath(os.path.dirname(os.path.realpath(__file__))))+"\\files"

def index(request):
    if request.user.is_authenticated:
        nb_user = User.objects.count() - 2
        nb_projects = Project.objects.count()
        nb_own = Project.objects.filter(user=request.user).count()
        truc = 0
        context = {'nb_user': nb_user, 'nb_projects': nb_projects, 'nb_own': nb_own, 'truc': truc}
        return render(request, 'appli/index.html', context)

    else:
        return HttpResponseRedirect('login/')
    

def addProject(request):
    if request.user.is_authenticated:

        if request.method == 'POST':

            form = ProjectForm(request.POST)
            if form.is_valid():

                proj = form.save(commit=False)

                extension = ''.join((proj.name).replace(" ", "")).lower()

                pull = pullrepo(proj.link, request.user.username, extension)

                if not pull:
                    
                    proj.user = request.user
                    proj.name = extension
                    proj.save()
                    return HttpResponseRedirect('appli/')
                else: 
                    context = {'message': 'Error : Try with a valid git repository'}
                    return render(request, 'appli/addproject.html', context)

        else:
            form = ProjectForm()
            context = {'form': form}
            return render(request, 'appli/addproject.html', context)

    else:
        return HttpResponseRedirect('login/')

def listProjects(request):
    if request.user.is_authenticated:

        all_projects = Project.objects.filter(user=request.user)
        context = {'all_projects': all_projects}
        return render(request, 'appli/listprojects.html', context)

    else:
        return HttpResponseRedirect('login/')

def detailProject(request, projectname):
    path = GLOBAL_DIRSTOCKAGE
    user_path = path+"\\"+request.user.username
    project_path = user_path+"\\"+projectname

    path, dirs, files = next(os.walk(project_path+"_BACKUPS"))
    file_count = len(files) 

    alldir=[]
    
    for path, subdirs, files in os.walk(project_path):
        if not path.split(os.path.sep)[-1] == ".git":
            directory = []
            level = path.replace(project_path, '').count(os.sep)
            directory.append(level)
            directory.append(os.path.basename(os.path.normpath(path)))
            directory.append(path)
            directory.append("folder")
            alldir.append(directory)
            subindent = (level + 1)

            realpath = path.replace('\\','/').split('/'+projectname, 1)[-1]+"/"

            for name in files:
                file = []
                file.append(subindent)
                file.append(name)

                url = realpath + name
                if url.startswith("/"):
                    url = url[1:]

                file.append(url)      
                file.append("file")
                alldir.append(file)
    context = {'alldir': alldir, 'projectname': projectname, 'nb_files':file_count}
    return render(request, 'appli/detailproject.html', context)

def showBackupsProject(request, projectname):
    path = GLOBAL_DIRSTOCKAGE
    user_path = path+"\\"+request.user.username
    project_path = user_path+"\\"+projectname+"_BACKUPS"

    alldir=[]
    if os.path.isdir(project_path):
        os.chdir(project_path)
        for file in glob.glob("*.zip"):
            c = strftime("%d-%m-%Y %H:%M", gmtime(float(creation_date(file))))
            alldir.append((file, c))
    context = {'alldir': alldir, 'projectname': projectname}
    return render(request, 'appli/listBackup.html', context)

def creation_date(path_to_file):
    if platform.system() == 'Windows':
        return os.path.getctime(path_to_file)
    else:
        stat = os.stat(path_to_file)
        try:
            return stat.st_birthtime
        except AttributeError:
            return stat.st_mtime

def modifyFile(request,projectname,filename):

    if request.user.is_authenticated:

        type = os.path.splitext(filename)[1][1:]
        switcher = {
            "html": "htmlmixed",
            "css": "css",
            "py": "python",
            "php": "php",
            "sql": "sql",
            "py": "python",
            "js": "javascript",
            "xml": "xml",
            "json": "javascript",
        }
        extension = switcher.get(type, "none")

        if request.POST.get("content", ""):

            content = '\n'.join([x for x in request.POST.get("content", "").splitlines() if x.strip()])

            setfile(request.user.username, projectname, filename, content)

        content = getfile(request.user.username, projectname, filename)
        
        context = {
            'projectname': projectname,
            'filename': filename,
            'extension': extension,
            'content': content
        }
        return render(request, 'appli/modifyFile.html', context)

def deleteProject(request, projectname):
    project = get_object_or_404(Project, name=projectname, user=request.user)
    deleterepo(request.user.username, projectname)
    Project.objects.filter(name=projectname).delete()
    return HttpResponseRedirect('/appli/project/')

def backupProject(request, projectname):
    project = get_object_or_404(Project, name=projectname, user=request.user)
    dobackup(request.user.username,projectname)
    return HttpResponseRedirect('/appli/project/'+projectname)

def restoreBackupProject(request, projectname, backupname):
    restorebackup(request.user.username, projectname, backupname)
    return HttpResponseRedirect('/appli/project/'+projectname)

def deleteBackupProject(request, projectname, backupname):
    deletebackup(request.user.username, projectname, backupname)
    return HttpResponseRedirect('/appli/project/backups/'+projectname)

#Commandes Python pures, pour la gestion des répertoires. Trouvables dans /functions.py (inutilisé). Coeur de notre projet puis intégrées en Django.
def pullrepo(url, username, projectname):

    path = GLOBAL_DIRSTOCKAGE
    user_path = path+"\\"+username
    project_path = user_path+"\\"+projectname


    if not os.path.exists(user_path):
        os.makedirs(user_path)

    if not os.path.exists(project_path):
        os.makedirs(project_path)
        os.makedirs(project_path+"_BACKUPS")

    try:
        Repo.clone_from(url, project_path)
    except Exception as e:
        error = 'Error! Type: {c}, Message, {m}'.format(c = type(e).__name__, m = str(e))
        return {'error':error}

def getfile(username, projectname, filename):

    path = GLOBAL_DIRSTOCKAGE.replace('\\','/')
    user_path = path+"/"+username
    project_path = user_path+"/"+projectname
    file_path =  project_path+"/"+filename

    with open(file_path, 'r') as myfile:
        data=myfile.read()
        print(data)
        return data

def setfile(username, projectname, filename, content):

    path = GLOBAL_DIRSTOCKAGE
    user_path = path+"\\"+username
    project_path = user_path+"\\"+projectname
    file_path =  project_path+"\\"+filename

    with open(file_path, 'w') as myfile:
        myfile.write(content)

def deleterepo(username, projectname):

    path = GLOBAL_DIRSTOCKAGE
    user_path = path+"\\"+username
    project_path = user_path+"\\"+projectname

    os.system('rmdir /S /Q "{}"'.format(project_path))
    os.system('rmdir /S /Q "{}"'.format(project_path+"_BACKUPS"))

def dobackup(username,projectname):
    path = GLOBAL_DIRSTOCKAGE
    user_path = path+"\\"+username
    project_path = user_path+"\\"+projectname

    date = datetime.datetime.fromtimestamp(time.time()).strftime('%Y%m%d_%H%M%S')
    zipname = user_path+"\\"+projectname+"_BACKUPS\\"+projectname+"_"+date+'.zip'

    zip_folder(project_path+"\\", zipname)

def zip_folder(folder_path, output_path):
    parent_folder = os.path.dirname(folder_path)
    contents = os.walk(folder_path)

    try:
        zip_file = zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED)
        for root, folders, files in contents:

            for folder_name in folders:
                absolute_path = os.path.join(root, folder_name)
                relative_path = absolute_path.replace(parent_folder + '\\','')
                zip_file.write(absolute_path, relative_path)

            for file_name in files:
                absolute_path = os.path.join(root, file_name)
                relative_path = absolute_path.replace(parent_folder + '\\','')
                zip_file.write(absolute_path, relative_path)
        zip_file.close()
    except zipfile.BadZipfile as message:
        sys.exit(1)


def restorebackup(username,projectname,backupname):
    path = GLOBAL_DIRSTOCKAGE
    user_path = path+"\\"+username
    project_path = user_path+"\\"+projectname
    backup_path = user_path+"\\"+projectname+"_BACKUPS\\"+backupname

    os.system('rmdir /S /Q "{}"'.format(project_path))
    os.makedirs(project_path)

    z = zipfile.ZipFile(backup_path, 'r')  
    z.extractall(project_path)  
    z.close()

def deletebackup(username,projectname,backupname):
    path = GLOBAL_DIRSTOCKAGE
    user_path = path+"\\"+username
    backup_path = user_path+"\\"+projectname+"_BACKUPS\\"+backupname

    os.remove(backup_path)









"""
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

appli/templates/appli/layouts/lateralbar.html
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            <li class="active">
                <a href="{% url 'appli:index' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="{% url 'appli:addProject' %}"><i class="fa fa-cogs fa-fw"></i> Start Project</a>
            </li>
            <li>
                <a style="cursor:pointer"><i class="fa fa-wrench fa-fw"></i> Last Projects<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    {% if last_proj %}
                        {% for proj in last_proj %}
                            <li><a href="{% url 'appli:detailProject' proj.name %}">{{ proj.name }}</a></li>
                        {% endfor %}
                    {% endif %}    
                    <li style="background-color:#F0F4F9;">
                        <a href="{% url 'appli:listProjects' %}"> All My Projects</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

appli/templates/appli/layouts/navbar.html
        
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'appli:index' %}">CodEdit <i class="fa fa-pencil" aria-hidden="true"></i></a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right" style="margin-top:0;">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-envelope fa-fw"></i> Contact Us</a>
                </li>
                <li class="divider"></li>
                <li><a href="{% url 'appli:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    {% include "appli/layouts/lateralbar.html" %}

</nav>